name: Update Coverage Badge
on:
  push:
    branches:
      - main  # Adjust the branch name as needed

jobs:
  update-badge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Run Jest with coverage
        run: npm test -- --coverage

      - name: Update Coverage Badge
        run: npx jest-badges coverage/coverage-final.json --file README.md --force-badge
